apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: x509-node-monitor
  namespace: monitoring
  labels:
    prometheus: k8s
spec:
  selector:
    matchLabels:
      app: x509-certificate-exporter-node
  namespaceSelector:
    matchNames:
      - monitoring
  endpoints:
  - port: metrics
    interval: 30s
    honorLabels: true
    path: /metrics
    relabelings:
      # เปลี่ยนจาก pod_node_name เป็น endpoint_node_name
      - sourceLabels: [__meta_kubernetes_endpoint_node_name]
        targetLabel: instance
        action: replace
